apiVersion: v1
kind: Pod

metadata:
  name: sweb-nginx
spec:
  containers:
    - image: balakrishnam/sweb-nginx:v0.0.1
      name: sweb-nginx
      ports:
      - containerPort: 8080
        protocol: TCP
