/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.clap;

import com.google.gson.JsonObject;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static JsonObject someAction (JsonObject arg) {
        JsonObject json = new JsonObject();
        json.addProperty("result", "Welcome to Serverless !");
        json.addProperty("status","SUCCESS");
        return json.getAsJsonObject();

        //todo: create fat jar from gradle
    }
}
